### ISSUE TITLE
Apps can't be rebundled beacuse the commits were removed

### ISSUE THREAD

**Issue by colinfish** [annkissam/date_as_string#1]
```
Fetching git@github.com:annkissam/date_as_string.git
fatal: Could not parse object '3644cdea2cdfc8a47c560b55da4a460542dd5cc3'.
Revision 3644cdea2cdfc8a47c560b55da4a460542dd5cc3 does not exist in the repository git@github.com:annkissam/date_as_string.git. Maybe you misspelled it?
```

**Comment by ericsullivan** [comment]
The were removed when this project was made public. We have the old code archived (if you'd like a link), but there are no compatibility issues with upgrading to the latest release

**Comment by colinfish** [comment]
Sounds good, thanks for the quick response.  We ported over the old gem, as deploys were not succeeding.  I think this is now a task for ET and elig-staging to update the gemfile and successfully deploy AlphaOne.
